search:
  areaIds: [1, 95, 76, 18]
  extendAreas: 2
  objectType: "Lägenhet"
  minListPrice: 1500000
  maxListPrice: 5700000
  minLivingArea: 25
  maxLivingArea: 70
  minRooms: 1.5
  maxRooms: 4

analysis:
  notifyThreshold: 70
  watchThreshold: 60
  maxEvaluations: 6
